# Generated by Django 6.0.2 on 2026-03-14 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('vehicleType', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10)),
                ('vehicleNumber', models.CharField(max_length=20)),
                ('vehicleModel', models.CharField(max_length=50)),
                ('vehicleYear', models.IntegerField(blank=True, null=True)),
                ('vehicleColor', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_profile',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDate', models.DateField()),
                ('bookingTime', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bookingStatus', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='garage.customerprofile')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.AutoField(primary_key=True, serialize=False)),
                ('notificationType', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_received', 'Payment Received'), ('service_completed', 'Service Completed'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], max_length=20)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transactionId', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentDate', models.DateTimeField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='garage.bookings')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceId', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceNumber', models.CharField(max_length=20, unique=True)),
                ('invoiceDate', models.DateField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discountAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='garage.bookings')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='garage.payments')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('providerId', models.AutoField(primary_key=True, serialize=False)),
                ('garageName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('garageImage', models.ImageField(blank=True, null=True, upload_to='garage_images/')),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('openingTime', models.TimeField()),
                ('closingTime', models.TimeField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('approvalStatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'serviceprovider',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='garage.bookings')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='garage.customerprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='garage.serviceprovider')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='garage.serviceprovider'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceId', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=100)),
                ('serviceDescription', models.TextField()),
                ('servicePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimatedDuration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('isAvailable', models.BooleanField(default=True)),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='garage.serviceprovider')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='garage.services'),
        ),
    ]
