# Generated by Django 6.0.2 on 2026-04-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='extraVehicles',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='vehicleModel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='vehicleNumber',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='vehicleType',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike')], default='car', max_length=10),
        ),
    ]
