# Generated by Django 6.0.2 on 2026-04-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_customerprofile_extravehicles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='vehicleType',
            field=models.CharField(choices=[('car', 'Car Only'), ('bike', 'Bike Only'), ('all', 'All Vehicles')], default='all', help_text='Which vehicle type this service applies to', max_length=10),
        ),
    ]
