# Generated by Django 6.0.2 on 2026-04-10 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_services_vehicletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='service',
        ),
        migrations.AddField(
            model_name='bookings',
            name='services',
            field=models.ManyToManyField(related_name='bookings', to='garage.services'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], default='car', max_length=10)),
                ('vehicleNumber', models.CharField(max_length=20)),
                ('vehicleModel', models.CharField(max_length=50)),
                ('vehicleYear', models.IntegerField(blank=True, null=True)),
                ('vehicleColor', models.CharField(blank=True, max_length=30, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='garage.customerprofile')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='garage.vehicle'),
        ),
    ]
